### ISSUE TITLE
Some Errors about this project

### ISSUE THREAD

**Issue by huangfei3095** [mslosarz/nextrtc-videochat-with-rest#4]
Hi, I am now studying on Next WebRtc project, and I found there are some errors on listed files:
    nextrtc\examples\videochat_with_rest\service  
                  RegisterUserService.java
                  SessionOpenedService.java
    nextrtc\examples\videochat_with_rest\domain
                  Member.java
    nextrtc\examples\videochat_with_rest\domain\handler
                  ConversationCreatedHandler.java
                  ExceptionHandler.java
   The errors are  log could not be resolved, xxx dao could not find xx method, etc.

```
I hope I could get the latest version that fixed all the bugs, Thanks.   
```

**Comment by huangfei3095** [comment]
I am now thinking of presenting  Web3D file which as large as 500G  on the Web, and I would consult you if it's possible to integrate Next WebRtc with JXTA2.7, so that the file could be transport from peer to peer instead of  integrated server. For  massive scale users request, peer to peer transportation WebRtc provided possible solution, and I am now consulting you about detailed information.

I am looking forward to hearing from you at your convinence.  my mail:  1254209774@qq.com

**Comment by chasd00** [comment]
The errors you are seeing are probably because of the lombok dependency. Please make sure you have it installed and configured for your IDE.
https://projectlombok.org/

**Comment by mslosarz** [comment]
Please add lombok project to your IDE and then rebuild application (did you
try build application using maven?)
11 lip 2016 02:41 "huangfei3095" <notifications@github.com> napisał(a):

Hi, I am now studying on Next WebRtc project, and I found there are some
errors on listed files:
nextrtc\examples\videochat_with_rest\service

RegisterUserService.java
SessionOpenedService.java
nextrtc\examples\videochat_with_rest\domain
Member.java
nextrtc\examples\videochat_with_rest\domain\handler
ConversationCreatedHandler.java
ExceptionHandler.java
The errors are log could not be resolved, xxx dao could not find xx method,
etc.

I hope I could get the latest version that fixed all the bugs, Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mslosarz/nextrtc-videochat-with-rest/issues/4>, or mute
the thread
<https://github.com/notifications/unsubscribe/ADysRbJRjQDWieAA9uY-0pBCWtBFMAJ9ks5qUZFDgaJpZM4JI9JA>
.
